---
title: "Roe_overall"
author: "Mitsuhiro Yuasa, Haryoon Kim"
date: "2024/04/08"
output: html_document
editor_options: 
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

##########
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
##########
```

```{r load libraries}
library(tidyverse)
library(epitools)
library(ComplexHeatmap)
library(circlize)
library(cowplot)
theme_set(theme_cowplot())
```

```{r make tst and directory}
tst <- "2023-08-29"

# pdf
outdir_pdf <- str_glue("result/REVISION/{tst}/4_Data_filt3/3_reclutser/9_Reannotation/16_Roe_overall/pdf")
dir.create(outdir_pdf, recursive = TRUE, showWarnings = FALSE)

# table
outdir_table <- str_glue("result/REVISION/{tst}/4_Data_filt3/3_reclutser/9_Reannotation/16_Roe_overall/table")
dir.create(outdir_table, recursive = TRUE, showWarnings = FALSE)

# Rds
outdir_Robj <- str_glue("result/REVISION/{tst}/4_Data_filt3/3_reclutser/9_Reannotation/16_Roe_overall/rds")
dir.create(outdir_Robj, recursive = TRUE, showWarnings = FALSE)
```

# 1. Preparation
```{r load metadata}
df_meta_overall <- read_tsv("result/REVISION/2023-08-29/4_Data_filt3/3_reclutser/9_Reannotation/06_integrate_subclusters/table/metadata_mouseNK_data_celltype_overall.txt")
```

```{r add diseasetype}
df_meta_for_freq <- df_meta_overall %>% 
  dplyr::select(cellbarcode2, gemname3, disease_type, disease_type2, celltype_overall, celltype_overall_detail) %>% 
  mutate(
    disease_type_edit = case_when(
      disease_type %in% c("mNK_SG", "mNK_Tu") ~ "SG/Other",
      disease_type == "mNK_SP"                ~ "SP"
    ),
    disease_type2_edit = case_when(
      disease_type2 %in% c("CreN_pre", "CreP_pre") ~ "Pre-tumor",
      disease_type2 == "CreP_Tumor"                ~ "Trp53-/- tumor",
      disease_type2 == "CreLMP1P_Tumor"            ~ "Trp53-/- LMP1+ tumor"
    ),
    disease_type3 = case_when(
      disease_type == "mNK_SG" & disease_type2 == "CreN_pre"       ~ "SG_CreN_pre",
      disease_type == "mNK_SG" & disease_type2 == "CreP_pre"       ~ "SG_CreP_pre",
      disease_type == "mNK_SP" & disease_type2 == "CreN_pre"       ~ "SP_CreN_pre",
      disease_type == "mNK_SP" & disease_type2 == "CreP_pre"       ~ "SP_CreP_pre",
      disease_type == "mNK_SG" & disease_type2 == "CreP_Tumor"     ~ "SG_CreP_LMPn_tumor",
      # disease_type == "mNK_SG" & disease_type2 == "CreLMP1P_Tumor" ~ "SG_CreP_LMPp_tumor",
      disease_type == "mNK_SP" & disease_type2 == "CreP_Tumor"     ~ "SP_CreP_LMPn_tumor",
      disease_type == "mNK_SP" & disease_type2 == "CreLMP1P_Tumor" ~ "SP_CreP_LMPp_tumor",
      disease_type == "mNK_Tu" & disease_type2 == "CreLMP1P_Tumor" ~ "Tu_CreP_LMPp_tumor"
    )
  ) %>% 
  mutate(
    disease_type = fct_relevel(disease_type, c("mNK_SG", "mNK_Tu", "mNK_SP")),
    disease_type_edit = fct_relevel(disease_type_edit, c("SG/Other", "SP")),
    disease_type2 = fct_relevel(disease_type2, c("CreN_pre", "CreP_pre", "CreP_Tumor", "CreLMP1P_Tumor")),
    disease_type2_edit = fct_relevel(disease_type2_edit, c("Pre-tumor", "Trp53-/- tumor", "Trp53-/- LMP1+ tumor")),
    celltype_overall = fct_relevel(celltype_overall, c("CD4T", "CD8T", "B", 
                                                       "Myeloid", "NK", "Other", 
                                                       "Tumor_LMPn", "Tumor_LMPp")),
    celltype_overall_detail = fct_relevel(celltype_overall_detail, 
                                          c("CD4T_N", "CD4T_EM", "TREG",
                                            "CD8T_N", "CD8T_CM", "CD8T_EM", "CD8T_RM", "CD8T_EX",
                                            "B_Immature", "B_Mature", "Plasmablast",
                                            "Mono", "Macro", "cDC1", "cDC2", "pDC", "mregDC", "MDSC",
                                            "NK", "Other", "Tumor_LMPn", "Tumor_LMPp")),
  )
```

# 2. Ro/e

## 2-1. Overall

```{r plot Ro/e}
celltype_axis <- c("celltype_overall")
diseasetype_axis <- c("disease_type_edit")

for (i in 1:length(celltype_axis)) {
  # i <- 1
  this_celltype_axis <- celltype_axis[i]
  
  for (j in 1:length(diseasetype_axis)) {
    # j <- 1
    this_diseasetype_axis <- diseasetype_axis[j]
    print(paste(this_celltype_axis, this_diseasetype_axis, sep = ", "))
    
    this_df_for_freq0 <- df_meta_for_freq %>% 
      filter(!get(this_celltype_axis) %in% c("Tumor_LMPn", "Tumor_LMPp")) %>% 
      dplyr::count(get(this_celltype_axis), get(this_diseasetype_axis))
    
    this_fct_levels <- setdiff(
      levels(this_df_for_freq0$`get(this_celltype_axis)`),
      c("Tumor_LMPn", "Tumor_LMPp")
    )
    
    this_df_for_freq_wide <- this_df_for_freq0 %>% 
      pivot_wider(names_from = `get(this_celltype_axis)`, 
                  values_from = n)
    this_df_for_freq_wide[is.na(this_df_for_freq_wide)] <- 0
    
    this_mat_for_Roe <- this_df_for_freq_wide %>% 
      dplyr::select(-`get(this_diseasetype_axis)`) %>% 
      as.matrix()
    rownames(this_mat_for_Roe) <- this_df_for_freq_wide$`get(this_diseasetype_axis)`
    
    this_mat_for_Roe_exp <- expected(this_mat_for_Roe)
    
    this_mat_for_Roe_diff <- this_mat_for_Roe / this_mat_for_Roe_exp
    
    # save matrix
    this_mat_for_Roe %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_obs_{this_celltype_axis}_by_{this_diseasetype_axis}.txt"))
    
    this_mat_for_Roe_exp %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_exp_{this_celltype_axis}_by_{this_diseasetype_axis}.txt"))
    
    this_mat_for_Roe_diff %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_diff_{this_celltype_axis}_by_{this_diseasetype_axis}.txt"))
    
    # binomial test
    this_vec_for_Roe <- as.vector(this_mat_for_Roe)
    this_vec_for_Roe_prob <- as.vector(this_mat_for_Roe_exp) / sum(this_vec_for_Roe)
    this_trials <- sum(this_vec_for_Roe)
    
    this_vec_for_Roe_binom <- vector()
    for (k in 1:length(this_vec_for_Roe)) {
      # k <- 1
      this_res_binom <- binom.test(x = this_vec_for_Roe[k], 
                                   n = this_trials, 
                                   p = this_vec_for_Roe_prob[k])
      this_vec_for_Roe_binom[k] <- this_res_binom$p.value
    }
    
    this_mat_for_Roe_binom_pval <- this_vec_for_Roe_binom
    dim(this_mat_for_Roe_binom_pval) <- dim(this_mat_for_Roe)
    dimnames(this_mat_for_Roe_binom_pval) <- dimnames(this_mat_for_Roe)
    this_mat_for_Roe_binom_pval %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_{this_celltype_axis}_by_{this_diseasetype_axis}_binom_pval.txt"))
    
    this_mat_for_Roe_binom_qval <- p.adjust(this_mat_for_Roe_binom_pval, method = "BH")
    dim(this_mat_for_Roe_binom_qval) <- dim(this_mat_for_Roe)
    dimnames(this_mat_for_Roe_binom_qval) <- dimnames(this_mat_for_Roe)
    this_mat_for_Roe_binom_qval %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_{this_celltype_axis}_by_{this_diseasetype_axis}_binom_qval.txt"))
    
    # matrix for Heatmap
    this_mat_for_Roe_diff2 <- this_mat_for_Roe_diff
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 3] <- "+++"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 2 & this_mat_for_Roe_diff < 3] <- "++"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 1.5 & this_mat_for_Roe_diff < 2] <- "+"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 0.67 & this_mat_for_Roe_diff < 1.5] <- "+-"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 0 & this_mat_for_Roe_diff < 0.67] <- "-"
    
    this_mat_for_Roe_diff2 <- this_mat_for_Roe_diff2[, colnames(this_mat_for_Roe_diff2) != "Other"]
    
    colors_fill <- c("darkslategray1", "cornsilk")
    
    # Heatmap
    fig <- Heatmap(this_mat_for_Roe_diff2, name = "mat", 
                   cluster_columns = FALSE,
                   cluster_rows = FALSE,
                   col = colors_fill,
                   show_heatmap_legend = FALSE,
                   cell_fun = function(j, i, x, y, width, height, fill) {
                     grid.text(this_mat_for_Roe_diff2[i, j], x, y, gp = gpar(fontsize = 20))
                   },
                   width = ncol(this_mat_for_Roe_diff2) * unit(20, "mm"), 
                   height = nrow(this_mat_for_Roe_diff2) * unit(20, "mm"),
                   rect_gp = gpar(lwd = 1.5))
    
    pdf(str_glue("{outdir_pdf}/Fig4c_Roe_{this_celltype_axis}_by_{this_diseasetype_axis}.pdf"))
    print(fig)
    dev.off()
  }
}
```

## 2-2. SG/Other

```{r plot Ro/e SG/Other}
df_meta_for_freq_SG_Other <- df_meta_for_freq %>% 
  filter(disease_type_edit == "SG/Other")

celltype_axis <- c("celltype_overall")
diseasetype_axis <- c("disease_type2_edit")

for (i in 1:length(celltype_axis)) {
  # i <- 1
  this_celltype_axis <- celltype_axis[i]
  
  for (j in 1:length(diseasetype_axis)) {
    # j <- 2
    this_diseasetype_axis <- diseasetype_axis[j]
    print(paste(this_celltype_axis, this_diseasetype_axis, sep = ", "))
    
    this_df_for_freq0 <- df_meta_for_freq_SG_Other %>% 
      filter(!get(this_celltype_axis) %in% c("Tumor_LMPn", "Tumor_LMPp")) %>% 
      dplyr::count(get(this_celltype_axis), get(this_diseasetype_axis))
    
    this_fct_levels <- setdiff(
      levels(this_df_for_freq0$`get(this_celltype_axis)`),
      c("Tumor_LMPn", "Tumor_LMPp")
    )
    
    this_df_for_freq_wide <- this_df_for_freq0 %>% 
      pivot_wider(names_from = `get(this_celltype_axis)`, 
                  values_from = n)
    this_df_for_freq_wide[is.na(this_df_for_freq_wide)] <- 0
    
    this_mat_for_Roe <- this_df_for_freq_wide %>% 
      dplyr::select(-`get(this_diseasetype_axis)`) %>% 
      as.matrix()
    rownames(this_mat_for_Roe) <- this_df_for_freq_wide$`get(this_diseasetype_axis)`
    
    this_mat_for_Roe_exp <- expected(this_mat_for_Roe)
    
    this_mat_for_Roe_diff <- this_mat_for_Roe / this_mat_for_Roe_exp
    
    # save matrix
    this_mat_for_Roe %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_obs_{this_celltype_axis}_SG_Other_by_{this_diseasetype_axis}.txt"))
    
    this_mat_for_Roe_exp %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_exp_{this_celltype_axis}_SG_Other_by_{this_diseasetype_axis}.txt"))
    
    this_mat_for_Roe_diff %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_diff_{this_celltype_axis}_SG_Other_by_{this_diseasetype_axis}.txt"))
    
    # binomial test
    this_vec_for_Roe <- as.vector(this_mat_for_Roe)
    this_vec_for_Roe_prob <- as.vector(this_mat_for_Roe_exp) / sum(this_vec_for_Roe)
    this_trials <- sum(this_vec_for_Roe)
    
    this_vec_for_Roe_binom <- vector()
    for (k in 1:length(this_vec_for_Roe)) {
      # k <- 1
      this_res_binom <- binom.test(x = this_vec_for_Roe[k], 
                                   n = this_trials, 
                                   p = this_vec_for_Roe_prob[k])
      this_vec_for_Roe_binom[k] <- this_res_binom$p.value
    }
    
    this_mat_for_Roe_binom_pval <- this_vec_for_Roe_binom
    dim(this_mat_for_Roe_binom_pval) <- dim(this_mat_for_Roe)
    dimnames(this_mat_for_Roe_binom_pval) <- dimnames(this_mat_for_Roe)
    this_mat_for_Roe_binom_pval %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_{this_celltype_axis}_SG_Other_by_{this_diseasetype_axis}_binom_pval.txt"))
    
    this_mat_for_Roe_binom_qval <- p.adjust(this_mat_for_Roe_binom_pval, method = "BH")
    dim(this_mat_for_Roe_binom_qval) <- dim(this_mat_for_Roe)
    dimnames(this_mat_for_Roe_binom_qval) <- dimnames(this_mat_for_Roe)
    this_mat_for_Roe_binom_qval %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_{this_celltype_axis}_SG_Other_by_{this_diseasetype_axis}_binom_qval.txt"))
    
    # matrix for Heatmap
    this_mat_for_Roe_diff2 <- this_mat_for_Roe_diff
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 3] <- "+++"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 2 & this_mat_for_Roe_diff < 3] <- "++"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 1.5 & this_mat_for_Roe_diff < 2] <- "+"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 0.67 & this_mat_for_Roe_diff < 1.5] <- "+-"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 0 & this_mat_for_Roe_diff < 0.67] <- "-"
    
    this_mat_for_Roe_diff2 <- this_mat_for_Roe_diff2[, colnames(this_mat_for_Roe_diff2) != "Other"]
    
    colors_fill <- c("darkslategray1", "orange1", "cornsilk", "red")
    
    # Heatmap
    fig <- Heatmap(this_mat_for_Roe_diff2, name = "mat", 
                   cluster_columns = FALSE,
                   cluster_rows = FALSE,
                   col = colors_fill,
                   show_heatmap_legend = FALSE,
                   cell_fun = function(j, i, x, y, width, height, fill) {
                     grid.text(this_mat_for_Roe_diff2[i, j], x, y, gp = gpar(fontsize = 20))
                   },
                   width = ncol(this_mat_for_Roe_diff2) * unit(20, "mm"), 
                   height = nrow(this_mat_for_Roe_diff2) * unit(20, "mm"),
                   rect_gp = gpar(lwd = 1.5))
    
    pdf(str_glue("{outdir_pdf}/Fig4c_Roe_{this_celltype_axis}_SG_Other_by_{this_diseasetype_axis}.pdf"))
    print(fig)
    dev.off()
  }
}
```

## 2-3. SP

```{r plot Ro/e SP}
df_meta_for_freq_SP <- df_meta_for_freq %>% 
  filter(disease_type_edit == "SP")

celltype_axis <- c("celltype_overall")
diseasetype_axis <- c("disease_type2_edit")

for (i in 1:length(celltype_axis)) {
  # i <- 1
  this_celltype_axis <- celltype_axis[i]
  
  for (j in 1:length(diseasetype_axis)) {
    # j <- 2
    this_diseasetype_axis <- diseasetype_axis[j]
    print(paste(this_celltype_axis, this_diseasetype_axis, sep = ", "))
    
    this_df_for_freq0 <- df_meta_for_freq_SP %>% 
      filter(!get(this_celltype_axis) %in% c("Tumor_LMPn", "Tumor_LMPp")) %>% 
      dplyr::count(get(this_celltype_axis), get(this_diseasetype_axis))
    
    this_fct_levels <- setdiff(
      levels(this_df_for_freq0$`get(this_celltype_axis)`),
      c("Tumor_LMPn", "Tumor_LMPp")
    )
    
    this_df_for_freq_wide <- this_df_for_freq0 %>% 
      pivot_wider(names_from = `get(this_celltype_axis)`, 
                  values_from = n)
    this_df_for_freq_wide[is.na(this_df_for_freq_wide)] <- 0
    
    this_mat_for_Roe <- this_df_for_freq_wide %>% 
      dplyr::select(-`get(this_diseasetype_axis)`) %>% 
      as.matrix()
    rownames(this_mat_for_Roe) <- this_df_for_freq_wide$`get(this_diseasetype_axis)`
    
    this_mat_for_Roe_exp <- expected(this_mat_for_Roe)
    
    this_mat_for_Roe_diff <- this_mat_for_Roe / this_mat_for_Roe_exp
    
    # save matrix
    this_mat_for_Roe %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_obs_{this_celltype_axis}_SP_by_{this_diseasetype_axis}.txt"))
    
    this_mat_for_Roe_exp %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_exp_{this_celltype_axis}_SP_by_{this_diseasetype_axis}.txt"))
    
    this_mat_for_Roe_diff %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_diff_{this_celltype_axis}_SP_by_{this_diseasetype_axis}.txt"))
    
    # binomial test
    this_vec_for_Roe <- as.vector(this_mat_for_Roe)
    this_vec_for_Roe_prob <- as.vector(this_mat_for_Roe_exp) / sum(this_vec_for_Roe)
    this_trials <- sum(this_vec_for_Roe)
    
    this_vec_for_Roe_binom <- vector()
    for (k in 1:length(this_vec_for_Roe)) {
      # k <- 1
      this_res_binom <- binom.test(x = this_vec_for_Roe[k], 
                                   n = this_trials, 
                                   p = this_vec_for_Roe_prob[k])
      this_vec_for_Roe_binom[k] <- this_res_binom$p.value
    }
    
    this_mat_for_Roe_binom_pval <- this_vec_for_Roe_binom
    dim(this_mat_for_Roe_binom_pval) <- dim(this_mat_for_Roe)
    dimnames(this_mat_for_Roe_binom_pval) <- dimnames(this_mat_for_Roe)
    this_mat_for_Roe_binom_pval %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_{this_celltype_axis}_SP_by_{this_diseasetype_axis}_binom_pval.txt"))
    
    this_mat_for_Roe_binom_qval <- p.adjust(this_mat_for_Roe_binom_pval, method = "BH")
    dim(this_mat_for_Roe_binom_qval) <- dim(this_mat_for_Roe)
    dimnames(this_mat_for_Roe_binom_qval) <- dimnames(this_mat_for_Roe)
    this_mat_for_Roe_binom_qval %>%
      as_tibble(rownames = this_diseasetype_axis) %>% 
      write_tsv(str_glue("{outdir_table}/mat_Roe_{this_celltype_axis}_SP_by_{this_diseasetype_axis}_binom_qval.txt"))
    
    # matrix for Heatmap
    this_mat_for_Roe_diff[, "CD8T"] <- NA
    
    this_mat_for_Roe_diff2 <- this_mat_for_Roe_diff
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 3] <- "+++"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 2 & this_mat_for_Roe_diff < 3] <- "++"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 1.5 & this_mat_for_Roe_diff < 2] <- "+"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 0.67 & this_mat_for_Roe_diff < 1.5] <- "+-"
    this_mat_for_Roe_diff2[this_mat_for_Roe_diff >= 0 & this_mat_for_Roe_diff < 0.67] <- "-"
    this_mat_for_Roe_diff2[is.na(this_mat_for_Roe_diff2)] <- ""
    
    this_mat_for_Roe_diff2 <- this_mat_for_Roe_diff2[, colnames(this_mat_for_Roe_diff2) != "Other"]
    
    colors_fill <- c("gray95", "darkslategray1", "orange1", "cornsilk", "red")
    
    # Heatmap
    fig <- Heatmap(this_mat_for_Roe_diff2, name = "mat", 
                   cluster_columns = FALSE,
                   cluster_rows = FALSE,
                   col = colors_fill,
                   show_heatmap_legend = FALSE,
                   cell_fun = function(j, i, x, y, width, height, fill) {
                     grid.text(this_mat_for_Roe_diff2[i, j], x, y, gp = gpar(fontsize = 20))
                   },
                   width = ncol(this_mat_for_Roe_diff2) * unit(20, "mm"), 
                   height = nrow(this_mat_for_Roe_diff2) * unit(20, "mm"),
                   rect_gp = gpar(lwd = 1.5))
    
    pdf(str_glue("{outdir_pdf}/Fig4c_Roe_{this_celltype_axis}_SP_by_{this_diseasetype_axis}.pdf"))
    print(fig)
    dev.off()
  }
}
```

```{r sessioninfo}
sessionInfo()
```
