---
title: "integrate_subclusters"
author: "Mitsuhiro Yuasa, Haryoon Kim"
date: "2024/03/27"
output: html_document
editor_options: 
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

##########
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
##########
```

```{r load libraries}
library(tidyverse)
library(gsubfn)
library(readxl)
library(RColorBrewer)
library(viridis)
library(ggsci)
library(grid)
library(gridExtra)
library(cowplot)
library(scales)
theme_set(theme_cowplot())
library(Seurat)
library(Matrix)
library(broom)
library(ggrepel)
library(presto)
```

```{r source}
source("R/utilities.R")
source("ref/cluster_annotation/cluster_annotation_level_220209.R")
```

```{r make tst and directory}
tst <- "2023-08-29"

# pdf
outdir_pdf <- str_glue("result/REVISION/{tst}/4_Data_filt3/3_reclutser/9_Reannotation/06_integrate_subclusters/pdf")
dir.create(outdir_pdf, recursive = TRUE, showWarnings = FALSE)

# table
outdir_table <- str_glue("result/REVISION/{tst}/4_Data_filt3/3_reclutser/9_Reannotation/06_integrate_subclusters/table")
dir.create(outdir_table, recursive = TRUE, showWarnings = FALSE)

# Rds
outdir_Robj <- str_glue("result/REVISION/{tst}/4_Data_filt3/3_reclutser/9_Reannotation/06_integrate_subclusters/rds")
dir.create(outdir_Robj, recursive = TRUE, showWarnings = FALSE)
```

# 1. Preparation
```{r load Seurat obj}
mouseNK_data <- readRDS("result/table/Robj/aggr/mouseNK_data_RNAdim45dim011_afterExclude_v1_other3660SP.rds")
this_dataset <- "mouseNK_CITEdata"
```

```{r load metadata}
Annotation_metadata_filt1_df <- read_tsv("result/table/2023-08-29/4_Data_filt3/1_UMAP/3_1_clustering_determine_cellsubset/mouseNK_annotationSeurat1_metadata.txt")

Annotation_metadata_filt1_df$cellbarcode2 %>% length()
```

```{r combine metadata}
Annotation_metadata_filt1_df %>% colnames()
mouseNK_data@meta.data %>% colnames()

setdiff(colnames(Annotation_metadata_filt1_df), colnames(mouseNK_data@meta.data))

unique(c("cellbarcode2", setdiff(colnames(Annotation_metadata_filt1_df), colnames(mouseNK_data@meta.data))))

annotation_df <- Annotation_metadata_filt1_df %>% 
  dplyr::select(
    unique(c("cellbarcode2", setdiff(colnames(Annotation_metadata_filt1_df), colnames(mouseNK_data@meta.data))))
  ) %>% 
  as.data.frame()
rownames(annotation_df) <- annotation_df$cellbarcode2
annotation_df %>% head()

mouseNK_data <- AddMetaData(object = mouseNK_data, metadata = annotation_df)

mouseNK_data$annotationSeurat1 <- factor(mouseNK_data$annotationSeurat1, levels = annotationSeurat1_NKmouse_filt2_level)
mouseNK_data$celltype1 <- factor(mouseNK_data$celltype1, levels = celltype1_NKmouse_filt2_level)
mouseNK_data$celltype2 <- factor(mouseNK_data$celltype2, levels = celltype2_NKmouse_filt2_level)
```

```{r add subclusters}
df_meta_T_NK <- read_tsv("result/REVISION/2023-08-29/4_Data_filt3/3_reclutser/9_Reannotation/01_subclustering_T_NK/table/metadata_mouseNK_subdata_T_NK_after_annotation_dim30res0050.txt")
df_meta_CD4T <- read_tsv("result/REVISION/2023-08-29/4_Data_filt3/3_reclutser/9_Reannotation/02_subclustering_CD4T/table/metadata_mouseNK_subdata_CD4T_after_annotation_dim30res0035.txt")
df_meta_CD8T <- read_tsv("result/REVISION/2023-08-29/4_Data_filt3/3_reclutser/9_Reannotation/03_subclustering_CD8T/table/metadata_mouseNK_subdata_CD8T_after_annotation_dim20res0020.txt")
df_meta_B <- read_tsv("result/REVISION/2023-08-29/4_Data_filt3/3_reclutser/9_Reannotation/04_subclustering_B/table/metadata_mouseNK_subdata_B_after_annotation_dim25res002.txt")
df_meta_Myeloid <- read_tsv("result/REVISION/2023-08-29/4_Data_filt3/3_reclutser/9_Reannotation/05_subclustering_Myeloid/table/metadata_mouseNK_subdata_Myeloid_after_annotation_dim25res008.txt")

df_meta_T_NK_select <- df_meta_T_NK %>% 
  dplyr::select(T_NK_subcluster, celltype_T_NK) %>% 
  as.data.frame()
rownames(df_meta_T_NK_select) <- df_meta_T_NK$cellbarcode2

df_meta_CD4T_select <- df_meta_CD4T %>% 
  dplyr::select(CD4T_subcluster, celltype_CD4T) %>% 
  as.data.frame()
rownames(df_meta_CD4T_select) <- df_meta_CD4T$cellbarcode2

df_meta_CD8T_select <- df_meta_CD8T %>% 
  dplyr::select(CD8T_subcluster, celltype_CD8T) %>% 
  as.data.frame()
rownames(df_meta_CD8T_select) <- df_meta_CD8T$cellbarcode2

df_meta_B_select <- df_meta_B %>% 
  dplyr::select(B_subcluster, celltype_B) %>% 
  as.data.frame()
rownames(df_meta_B_select) <- df_meta_B$cellbarcode2

df_meta_Myeloid_select <- df_meta_Myeloid %>% 
  dplyr::select(Myeloid_subcluster, celltype_Myeloid) %>% 
  as.data.frame()
rownames(df_meta_Myeloid_select) <- df_meta_Myeloid$cellbarcode2

mouseNK_data <- AddMetaData(object = mouseNK_data, metadata = df_meta_T_NK_select)
mouseNK_data <- AddMetaData(object = mouseNK_data, metadata = df_meta_CD4T_select)
mouseNK_data <- AddMetaData(object = mouseNK_data, metadata = df_meta_CD8T_select)
mouseNK_data <- AddMetaData(object = mouseNK_data, metadata = df_meta_B_select)
mouseNK_data <- AddMetaData(object = mouseNK_data, metadata = df_meta_Myeloid_select)
```

```{r add celltypes}
mouseNK_data@meta.data$celltype1 %>% unique()
mouseNK_data@meta.data$celltype2 %>% unique()
mouseNK_data@meta.data$celltype_T_NK %>% unique()
mouseNK_data@meta.data$celltype_CD4T %>% unique()
mouseNK_data@meta.data$celltype_CD8T %>% unique()
mouseNK_data@meta.data$celltype_B %>% unique()
mouseNK_data@meta.data$celltype_Myeloid %>% unique()

mouseNK_data@meta.data <- mouseNK_data@meta.data %>% 
  mutate(
    celltype_overall = case_when(
      !is.na(celltype_T_NK) & celltype_T_NK == "CD4T" ~ "CD4T",
      !is.na(celltype_T_NK) & celltype_T_NK == "CD8T" ~ "CD8T",
      !is.na(celltype_T_NK) & celltype_T_NK == "NK"   ~ "NK",
      !is.na(celltype2) & celltype2 == "B"            ~ "B",
      !is.na(celltype2) & celltype2 == "Myeloid"      ~ "Myeloid",
      !is.na(celltype1) & celltype1 == "Tumor_LMPn"   ~ "Tumor_LMPn",
      !is.na(celltype1) & celltype1 == "Tumor_LMPp"   ~ "Tumor_LMPp",
      TRUE                                            ~ "Other"
    ),
    celltype_overall_detail = case_when(
      !is.na(celltype_CD4T)                         ~ celltype_CD4T,
      !is.na(celltype_CD8T)                         ~ celltype_CD8T,
      !is.na(celltype_T_NK) & celltype_T_NK == "NK" ~ "NK",
      !is.na(celltype_B)                            ~ celltype_B,
      !is.na(celltype_Myeloid)                      ~ celltype_Myeloid,
      !is.na(celltype1) & celltype1 == "Tumor_LMPn" ~ "Tumor_LMPn",
      !is.na(celltype1) & celltype1 == "Tumor_LMPp" ~ "Tumor_LMPp",
      TRUE                                          ~ "Other"
    )
  ) %>% 
  mutate(
    celltype_overall = fct_relevel(celltype_overall, c("CD4T", "CD8T", "B", 
                                                       "Myeloid", "NK", "Other", 
                                                       "Tumor_LMPn", "Tumor_LMPp")),
    celltype_overall_detail = fct_relevel(celltype_overall_detail, 
                                          c("CD4T_N", "CD4T_EM", "TREG",
                                            "CD8T_N", "CD8T_CM", "CD8T_EM", "CD8T_RM", "CD8T_EX",
                                            "B_Immature", "B_Mature", "Plasmablast",
                                            "Mono", "Macro", "cDC1", "cDC2", "pDC", "mregDC", "MDSC",
                                            "NK", "Other", "Tumor_LMPn", "Tumor_LMPp")),
  )
```


# 2. UMAP
```{r UMAP}
ggColorHue <- function(n, l = 65) {
  hues <- seq(15, 375, length = n + 1)
  hcl(h = hues, l = l, c = 100)[1:n]
}

cols <- ggColorHue(n = 8)
col2rgb(cols)
scales::show_col(cols)

cols <- cols[c(1, 2, 5, 6, 4, 3, 7, 8)]
scales::show_col(cols)

p1 <- DimPlot(mouseNK_data, reduction = 'umap', 
              group.by = "celltype_overall",
              label = TRUE, repel = TRUE, 
              raster = TRUE, raster.dpi = c(600, 600)) + 
  labs(title = "UMAP: celltype_overall") +
  theme(plot.title = element_text(size = 15)) +
  scale_color_manual(values = cols)

p2 <- DimPlot(mouseNK_data, reduction = 'umap', 
              group.by = "celltype_overall",
              label = FALSE, repel = TRUE, 
              raster = TRUE, raster.dpi = c(600, 600)) + 
  labs(title = "UMAP: celltype_overall") +
  theme(plot.title = element_text(size = 15)) +
  scale_color_manual(values = cols)

p3 <- DimPlot(mouseNK_data, reduction = 'umap', 
              group.by = "celltype_overall_detail",
              label = TRUE, repel = TRUE, 
              raster = TRUE, raster.dpi = c(600, 600)) + 
  labs(title = "UMAP: celltype_overall_detail") +
  theme(plot.title = element_text(size = 15))

p4 <- DimPlot(mouseNK_data, reduction = 'umap', 
              group.by = "celltype_overall_detail",
              label = FALSE, repel = TRUE, 
              raster = TRUE, raster.dpi = c(600, 600)) + 
  labs(title = "UMAP: celltype_overall_detail") +
  theme(plot.title = element_text(size = 15))

p5 <- DimPlot(mouseNK_data, reduction = 'umap', 
              group.by = "gemname3",
              label = FALSE, repel = TRUE, 
              raster = TRUE, raster.dpi = c(600, 600)) + 
  labs(title = "UMAP: 17 samples") +
  theme(plot.title = element_text(size = 15))

p6 <- DimPlot(mouseNK_data, reduction = 'umap', 
              group.by = "disease_type2",
              label = FALSE, repel = TRUE, 
              raster = TRUE, raster.dpi = c(600, 600)) + 
  labs(title = "UMAP: disease types") +
  theme(plot.title = element_text(size = 15))

pdf(str_glue("{outdir_pdf}/Fig4b_UMAP_celltype_overall_.pdf"))
print(p1)
print(p1 + NoLegend())
print(p2 + NoLegend())
print(p3)
print(p3 + NoLegend())
print(p4 + NoLegend())
print(p5)
print(p5 + NoLegend())
print(p6)
print(p6 + NoLegend())
dev.off()

# UMAP gene markers
known_genes <- read_tsv("ref/cluster_ref_genes/genes_for_bubbleplot_celltype4.txt")
known_genes_included <- known_genes$gene[known_genes$gene %in% rownames(mouseNK_data[["SCT"]])]

pdf(str_glue("{outdir_pdf}/UMAP_overall_subcluster_known_genes.pdf"))
for (i in 1:length(known_genes_included)) {
  # i <- 19
  this_gene <- known_genes_included[i]
  p <- FeaturePlot(mouseNK_data, features = this_gene, 
                   raster = TRUE, pt.size = 2.5, raster.dpi = c(600, 600))
  print(p)
}
dev.off()
```

# 3. Dotplot
```{r Dotplot}
df_genes <- read_tsv("ref/cluster_ref_genes/genes_for_bubbleplot_REVISION/genes_for_bubbleplot_celltype_overall.txt")

Idents(mouseNK_data) <- mouseNK_data$celltype_overall

fig1 <- DotPlot(object = mouseNK_data,
                assay = 'SCT',
                idents = c("CD4T", "CD8T", "B", "Myeloid", "NK", "Tumor_LMPn", "Tumor_LMPp"),
                features = rev(unique(df_genes$gene)), 
                cols = c("lightgrey", "red"),
                col.min = 0.1,
                col.max = 2,
                scale.min = 20,
                scale.max = 100,
                cluster.idents = FALSE) + 
  theme(axis.text.x = element_text(size = 10, 
                                   angle = 90,
                                   vjust = 0.5,
                                   hjust = 1)) +
  xlab("") +
  ylab("") +
  coord_flip()

pdf(str_glue("{outdir_pdf}/FigS5d_Dotplot_celltype_overall_for_manuscript_scaled.pdf"), height = 10)
print(fig1)
dev.off()
```

# 4. Save
```{r save metadata}
mouseNK_data@meta.data %>% 
  as_tibble() %>% 
  write_tsv(str_glue("{outdir_table}/metadata_mouseNK_data_celltype_overall.txt"))
```

```{r save for suppl table}
mouseNK_data@meta.data %>% 
  dplyr::count(gemname3, celltype_overall) %>% 
  pivot_wider(names_from = gemname3, values_from = n) %>% 
  filter(celltype_overall != "Other") %>% 
  write_tsv(str_glue("{outdir_table}/S7_mu_sc_cluster.txt"))

mouseNK_data@meta.data %>% 
  dplyr::count(gemname3, celltype_overall_detail) %>% 
  pivot_wider(names_from = gemname3, values_from = n) %>% 
  filter(!celltype_overall_detail %in% c("Other", "Tumor_LMPn", "Tumor_LMPp")) %>% 
  write_tsv(str_glue("{outdir_table}/S7_mu_sc_cluster_detail.txt"))
```

# 5. Tumor NK vs Normal NK
```{r NK subdata}
unique(mouseNK_data$celltype_overall)
Idents(mouseNK_data) <- mouseNK_data$celltype_overall

mouseNK_subdata <- subset(x = mouseNK_data, idents = c("NK", "Tumor_LMPn", "Tumor_LMPp"))

mouseNK_subdata@meta.data <- mouseNK_subdata@meta.data %>% 
  mutate(celltype_NK = if_else(celltype_overall == "NK", "Normal_NK", "Tumor_NK"),
         celltype_NK = fct_relevel(celltype_NK, c("Normal_NK", "Tumor_NK")))

unique(mouseNK_subdata$celltype_NK)
Idents(mouseNK_subdata) <- mouseNK_subdata$celltype_NK

DefaultAssay(mouseNK_subdata) <- 'SCT'
```

```{r NK dotplot}
df_NK_genes <- read_tsv("ref/cluster_ref_genes/NK_BasicCellSubset_genes3_selected_231010.txt")

NK_genes <- df_NK_genes$gene

fig <- DotPlot2(object = mouseNK_subdata,
                assay = 'SCT',
                features = rev(unique(NK_genes)),
                cols = c("lightgrey", "red"),
                scale = FALSE,
                col.min = 0.1,
                col.max = 1.5,
                scale.min = 10,
                scale.max = 80,
                cluster.idents = FALSE) + 
  theme(axis.text.x = element_text(size = 10, 
                                   angle = 90,
                                   vjust = 0.5,
                                   hjust = 1)) +
  xlab("") +
  ylab("") +
  coord_flip()

pdf(str_glue("{outdir_pdf}/Fig6a_Dotplot_Normal_NK_vs_Tumor_NK_not_scaled.pdf"), height = 10)
print(fig)
dev.off()
```

```{r sessioninfo}
sessionInfo()
```
